#!/usr/bin/env bash
# Tool Name :- IP-Tracer


case "$1" in
  -m)
    php modules/.tracem.php
  ;;
  -t)
    case "$#" in
    2)
      php modules/.traceip.php $2
    ;;
    *)
      echo "error : invalid arguments !!"
      echo "use: ip-tracer -t <target_ip>"
    ;;
    esac
  ;;
  -u)
    php modules/.update.php
    exit
  ;;
  update)
    php modules/.update.php
    exit
  ;;
  start)
    php .IP-Tracer.php
    exit
  ;;
  -rm)
    php modules/.uninstall.php
    exit
  ;;
  *)
    echo "Usage: ip-tracer [command]... [arguments]..."
    echo " Commands:"
    echo " -t <target_ip>      to trace target ip."
    echo " -m                  to trace your own ip."
    echo " -h                  to show help."
    echo " -u                  to update ip-tracer."
    echo " help                to show help."
    echo " update              to update ip-tracer."
    echo " start               to start ip-tracer menu."
esac#!/usr/bin/env bash
# Tool Name :- IP-Tracer


case "$1" in
  -m)
    php modules/.tracem.php
  ;;
  -t)
    case "$#" in
    2)
      php modules/.traceip.php $2
    ;;
    *)
      echo "error : invalid arguments !!"
      echo "use: ip-tracer -t <target_ip>"
    ;;
    esac
  ;;
  -u)
    php modules/.update.php
    exit
  ;;
  update)
    php modules/.update.php
    exit
  ;;
  start)
    php .IP-Tracer.php
    exit
  ;;
  -rm)
    php modules/.uninstall.php
    exit
  ;;
  *)
  echo "Uso: ip-tracer [comando]... [argumentos]..."
    echo "Comandos:"
    echo " -t <target_ip> para rastrear o ip de destino."
    echo "-m para rastrear seu próprio ip."
    echo "-h para mostrar ajuda."
    echo "-u para atualizar o ip-tracer."
    echo "ajuda para mostrar ajuda."
    echo "atualizar para atualizar o ip-tracer."
    echo "começar a iniciar o menu ip-tracer."
esac
